# Enable C++ support
language: cpp
# Dependencies
install:
  - sudo apt-get install libsdl2-2.0.4
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
